import os
import torch
import torch.nn as nn
import numpy as np
import time
import gc
import json
from torchvision import datasets, transforms
from mnist_ratio_utils import load_models, convert_to_snn, get_mnist_ratio_dataloaders, load_temporal_models
from mnist_snn_loading import get_snn_autoencoder_dataloaders
from inference_comparison import create_dataloaders_for_comparison, measure_ann_inference_time, measure_rate_snn_inference_time, measure_temporal_snn_inference_time
import matplotlib.pyplot as plt
from tqdm import tqdm

def count_neurons(model):
    """Count the number of neurons in a model."""
    total_neurons = 0
    
    for module in model.modules():
        if isinstance(module, (nn.Linear, nn.Conv1d, nn.Conv2d)):
            total_neurons += module.out_features if hasattr(module, 'out_features') else module.out_channels
        elif hasattr(module, 'spiking_model'):
            # For sinabs models, count neurons in the spiking model
            for submodule in module.spiking_model.modules():
                if isinstance(submodule, (nn.Linear, nn.Conv1d, nn.Conv2d)):
                    total_neurons += submodule.out_features if hasattr(submodule, 'out_features') else submodule.out_channels
    
    return total_neurons

def count_synapses(model):
    """Count the number of synapses (parameters) in a model."""
    total_params = 0
    
    for param in model.parameters():
        total_params += param.numel()
    
    return total_params

def count_spikes_in_snn_model(model, dataloader, device, num_batches=5, model_type='temporal'):
    """Count total spikes generated by SNN model during inference."""
    model = model.to(device)
    model.eval()
    
    total_spikes = 0
    spike_hooks = []
    
    def sinabs_spike_counter_hook(module, input, output):
        nonlocal total_spikes
        if isinstance(output, torch.Tensor):
            # For sinabs models, spikes are binary values
            total_spikes += output.sum().item()
    
    def snntorch_spike_counter_hook(module, input, output):
        nonlocal total_spikes
        if isinstance(output, torch.Tensor):
            # For snntorch models, count spikes
            total_spikes += output.sum().item()
        elif isinstance(output, tuple) and len(output) >= 1:
            # snntorch sometimes returns (spikes, membrane_potential)
            spikes = output[0]
            if isinstance(spikes, torch.Tensor):
                total_spikes += spikes.sum().item()
    
    # Register hooks based on model type
    if hasattr(model, 'spiking_model'):
        # Rate-encoded model (sinabs)
        for module in model.spiking_model.modules():
            if 'spike' in module.__class__.__name__.lower() or hasattr(module, 'spike_fn'):
                hook = module.register_forward_hook(sinabs_spike_counter_hook)
                spike_hooks.append(hook)
    else:
        # Temporal model (snntorch)
        import snntorch as snn
        for module in model.modules():
            if isinstance(module, snn.Leaky):
                hook = module.register_forward_hook(snntorch_spike_counter_hook)
                spike_hooks.append(hook)
    
    with torch.no_grad():
        for batch_idx, batch_data in enumerate(dataloader):
            if batch_idx >= num_batches:
                break
            
            if model_type == 'temporal':  # temporal data
                spikes, _, _ = batch_data
                spikes = spikes.to(device)
                _ = model(spikes)
            else:  # rate-encoded data
                data, _ = batch_data
                data = data.to(device)
                batch_size = data.shape[0]
                
                # Create rate-encoded input
                num_timesteps = 100
                input_spikes = (torch.rand(num_timesteps, batch_size, 784, device=device) < data.unsqueeze(0)).float()
                
                # Reset state
                if hasattr(model, 'reset'):
                    model.reset()
                elif hasattr(model, 'reset_states'):
                    model.reset_states()
                
                # Pass input to model
                if hasattr(model, 'spiking_model'):
                    _ = model.spiking_model(input_spikes.reshape(-1, 784))
                else:
                    _ = model(input_spikes)
    
    # Remove hooks
    for hook in spike_hooks:
        hook.remove()
    
    return total_spikes

def measure_inference_with_spikes_improved(model, dataloader, device, num_batches=5, model_type='temporal'):
    """Measure inference time and count spikes for SNN models with improved spike detection."""
    model = model.to(device)
    model.eval()
    
    times = []
    total_spikes = 0
    spike_hooks = []
    
    def sinabs_spike_counter_hook(module, input, output):
        nonlocal total_spikes
        if isinstance(output, torch.Tensor):
            total_spikes += output.sum().item()
    
    def snntorch_spike_counter_hook(module, input, output):
        nonlocal total_spikes
        if isinstance(output, torch.Tensor):
            total_spikes += output.sum().item()
        elif isinstance(output, tuple) and len(output) >= 1:
            spikes = output[0]
            if isinstance(spikes, torch.Tensor):
                total_spikes += spikes.sum().item()
    
    # Register hooks based on model type
    if hasattr(model, 'spiking_model'):
        # Rate-encoded model (sinabs)
        for module in model.spiking_model.modules():
            if 'spike' in module.__class__.__name__.lower() or hasattr(module, 'spike_fn'):
                hook = module.register_forward_hook(sinabs_spike_counter_hook)
                spike_hooks.append(hook)
    else:
        # Temporal model (snntorch)
        import snntorch as snn
        for module in model.modules():
            if isinstance(module, snn.Leaky):
                hook = module.register_forward_hook(snntorch_spike_counter_hook)
                spike_hooks.append(hook)
    
    with torch.no_grad():
        for batch_idx, batch_data in enumerate(dataloader):
            if batch_idx >= num_batches:
                break
            
            start_time = time.time()
            
            if model_type == 'temporal':  # temporal data
                spikes, _, _ = batch_data
                spikes = spikes.to(device)
                _ = model(spikes)
            else:  # rate-encoded data
                data, _ = batch_data
                data = data.to(device)
                batch_size = data.shape[0]
                
                # Create rate-encoded input
                num_timesteps = 100
                input_spikes = (torch.rand(num_timesteps, batch_size, 784, device=device) < data.unsqueeze(0)).float()
                
                # Reset state
                if hasattr(model, 'reset'):
                    model.reset()
                elif hasattr(model, 'reset_states'):
                    model.reset_states()
                
                # Pass input to model
                if hasattr(model, 'spiking_model'):
                    _ = model.spiking_model(input_spikes.reshape(-1, 784))
                else:
                    _ = model(input_spikes)
            
            end_time = time.time()
            times.append(end_time - start_time)
    
    # Remove hooks
    for hook in spike_hooks:
        hook.remove()
    
    avg_time = np.mean(times)
    time_per_spike = avg_time / total_spikes if total_spikes > 0 else 0
    
    return avg_time, total_spikes, time_per_spike

def calculate_all_statistics(batch_sizes=[16, 32, 64, 128]):
    """Calculate all requested statistics."""
    
    device = torch.device("mps" if torch.backends.mps.is_available() else 
                         "cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    
    # Load models
    print("Loading models...")
    ann_models = load_models()
    ann_to_snn_models = [convert_to_snn(model, num_steps=100) for model in ann_models]
    temporal_models = load_temporal_models()
    
    # Create dataloaders
    print("Creating dataloaders...")
    ann_loaders, rate_loaders, temporal_loaders = create_dataloaders_for_comparison(batch_sizes)
    
    results = {
        'neurons': {
            'ann': [],
            'rate_snn': [],
            'temporal_snn': []
        },
        'synapses': {
            'ann': [],
            'rate_snn': [],
            'temporal_snn': []
        },
        'inference_times': {
            'ann': {bs: [] for bs in batch_sizes},
            'rate_snn': {bs: [] for bs in batch_sizes},
            'temporal_snn': {bs: [] for bs in batch_sizes}
        },
        'spikes': {
            'rate_snn': {bs: [] for bs in batch_sizes},
            'temporal_snn': {bs: [] for bs in batch_sizes}
        },
        'time_per_spike': {
            'rate_snn': {bs: [] for bs in batch_sizes},
            'temporal_snn': {bs: [] for bs in batch_sizes}
        },
        'model_names': {
            'ann': [model.__class__.__name__ for model in ann_models],
            'rate_snn': [f"Rate_{model.__class__.__name__}" for model in ann_models],
            'temporal_snn': [f"Temporal_{model.__class__.__name__}" for model in temporal_models]
        }
    }
    
    # 1. Count neurons
    print("\n1. Counting neurons...")
    for model in ann_models:
        neurons = count_neurons(model)
        results['neurons']['ann'].append(neurons)
        print(f"  ANN {model.__class__.__name__}: {neurons} neurons")
    
    for model in ann_to_snn_models:
        neurons = count_neurons(model)
        results['neurons']['rate_snn'].append(neurons)
        print(f"  Rate SNN {model.__class__.__name__}: {neurons} neurons")
    
    for model in temporal_models:
        neurons = count_neurons(model)
        results['neurons']['temporal_snn'].append(neurons)
        print(f"  Temporal SNN {model.__class__.__name__}: {neurons} neurons")
    
    # 2. Count synapses
    print("\n2. Counting synapses...")
    for model in ann_models:
        synapses = count_synapses(model)
        results['synapses']['ann'].append(synapses)
        print(f"  ANN {model.__class__.__name__}: {synapses} synapses")
    
    for model in ann_to_snn_models:
        synapses = count_synapses(model)
        results['synapses']['rate_snn'].append(synapses)
        print(f"  Rate SNN {model.__class__.__name__}: {synapses} synapses")
    
    for model in temporal_models:
        synapses = count_synapses(model)
        results['synapses']['temporal_snn'].append(synapses)
        print(f"  Temporal SNN {model.__class__.__name__}: {synapses} synapses")
    
    # 3. Measure inference times
    print("\n3. Measuring inference times...")
    for batch_size in batch_sizes:
        print(f"  Batch size {batch_size}:")
        
        # ANN models
        for model_idx, model in enumerate(ann_models):
            avg_time, _ = measure_ann_inference_time(model, ann_loaders[batch_size], device, num_batches=5)
            results['inference_times']['ann'][batch_size].append(avg_time)
            print(f"    ANN {model.__class__.__name__}: {avg_time:.4f}s")
        
        # Rate SNN models
        for model_idx, model in enumerate(ann_to_snn_models):
            avg_time, total_spikes, time_per_spike = measure_inference_with_spikes_improved(model, rate_loaders[batch_size], device, num_batches=5, model_type='rate')
            results['inference_times']['rate_snn'][batch_size].append(avg_time)
            results['spikes']['rate_snn'][batch_size].append(total_spikes)
            results['time_per_spike']['rate_snn'][batch_size].append(time_per_spike)
            print(f"    Rate SNN {ann_models[model_idx].__class__.__name__}: {avg_time:.4f}s, {total_spikes} spikes, {time_per_spike:.8f}s/spike")
        
        # Temporal SNN models
        for model_idx, model in enumerate(temporal_models):
            avg_time, total_spikes, time_per_spike = measure_inference_with_spikes_improved(model, temporal_loaders[batch_size], device, num_batches=5, model_type='temporal')
            results['inference_times']['temporal_snn'][batch_size].append(avg_time)
            results['spikes']['temporal_snn'][batch_size].append(total_spikes)
            results['time_per_spike']['temporal_snn'][batch_size].append(time_per_spike)
            print(f"    Temporal SNN {model.__class__.__name__}: {avg_time:.4f}s, {total_spikes} spikes, {time_per_spike:.8f}s/spike")
    
    return results

def visualize_statistics(results, save_dir="../plots"):
    """Create comprehensive visualizations of all statistics."""
    
    os.makedirs(save_dir, exist_ok=True)
    
    # Create figure with only 2 subplots (1 row, 2 columns)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
    
    # Get batch sizes
    batch_sizes = list(results['inference_times']['ann'].keys())
    if isinstance(batch_sizes[0], str):
        batch_sizes = [int(bs) for bs in batch_sizes]
    batch_sizes.sort()
    
    # 1. Inference Times vs Batch Size
    ann_times = [np.mean(results['inference_times']['ann'][bs]) for bs in batch_sizes]
    rate_snn_times = [np.mean(results['inference_times']['rate_snn'][bs]) for bs in batch_sizes]
    temporal_snn_times = [np.mean(results['inference_times']['temporal_snn'][bs]) for bs in batch_sizes]
    
    ax1.plot(batch_sizes, ann_times, 'o-', label='ANN', linewidth=2, color='blue')
    ax1.plot(batch_sizes, rate_snn_times, 's-', label='Rate SNN', linewidth=2, color='orange')
    ax1.plot(batch_sizes, temporal_snn_times, '^-', label='Temporal SNN', linewidth=2, color='green')
    ax1.set_xlabel('Batch Size')
    ax1.set_xticks(batch_sizes)
    ax1.set_ylabel('Average Inference Time (s)')
    ax1.set_title('Inference Time vs Batch Size')
    ax1.legend()
    ax1.grid(True)
    ax1.set_yscale('log')
    
    # 2. Total Spikes vs Batch Size
    rate_spikes = [np.mean(results['spikes']['rate_snn'][bs]) for bs in batch_sizes]
    temporal_spikes = [np.mean(results['spikes']['temporal_snn'][bs]) for bs in batch_sizes]
    
    ax2.plot(batch_sizes, rate_spikes, 's-', label='Rate SNN', linewidth=2, color='orange')
    ax2.plot(batch_sizes, temporal_spikes, '^-', label='Temporal SNN', linewidth=2, color='green')
    ax2.set_xlabel('Batch Size')
    ax2.set_xticks(batch_sizes)
    ax2.set_ylabel('Total Spikes')
    ax2.set_title('Total Spikes vs Batch Size')
    ax2.legend()
    ax2.grid(True)
    
    plt.tight_layout()
    plt.savefig(f"{save_dir}/comprehensive_statistics.png", dpi=300, bbox_inches='tight')
    plt.close()
    
    # 4. Time per Spike Analysis
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
    
    # 1. Inference Time per Spike vs Batch Size
    rate_time_per_spike = [np.mean(results['time_per_spike']['rate_snn'][bs]) for bs in batch_sizes]
    temporal_time_per_spike = [np.mean(results['time_per_spike']['temporal_snn'][bs]) for bs in batch_sizes]
    
    ax1.plot(batch_sizes, rate_time_per_spike, 's-', label='Rate SNN', linewidth=2, color='orange')
    ax1.plot(batch_sizes, temporal_time_per_spike, '^-', label='Temporal SNN', linewidth=2, color='green')
    ax1.set_xlabel('Batch Size')
    ax1.set_xticks(batch_sizes)
    ax1.set_ylabel('Time per Spike (s)')
    ax1.set_title('Inference Time per Spike vs Batch Size')
    ax1.legend()
    ax1.grid(True)
    ax1.set_yscale('log')
    
    # 2. Spike Processing Efficiency (spikes per second)
    if batch_sizes and len(rate_spikes) > 0 and len(rate_snn_times) > 0:
        rate_efficiency = [spikes/time for spikes, time in zip(rate_spikes, rate_snn_times)]
        temporal_efficiency = [spikes/time for spikes, time in zip(temporal_spikes, temporal_snn_times)]
        
        ax2.plot(batch_sizes, rate_efficiency, 's-', label='Rate SNN', linewidth=2, color='orange')
        ax2.plot(batch_sizes, temporal_efficiency, '^-', label='Temporal SNN', linewidth=2, color='green')
        ax2.set_xlabel('Batch Size')
        ax2.set_xticks(batch_sizes)
        ax2.set_ylabel('Spikes per Second')
        ax2.set_title('Spike Processing Efficiency')
        ax2.legend()
        ax2.grid(True)
    
    plt.tight_layout()
    plt.savefig(f"{save_dir}/spike_analysis.png", dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Visualizations saved to {save_dir}/")

def save_statistics(results, filename="../results/comprehensive_statistics.json"):
    """Save all statistics to JSON file."""
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    # Convert to JSON-serializable format
    json_results = {}
    for key, value in results.items():
        if isinstance(value, dict):
            json_results[key] = {}
            for subkey, subvalue in value.items():
                if isinstance(subvalue, dict):
                    json_results[key][subkey] = {str(k): v for k, v in subvalue.items()}
                else:
                    json_results[key][subkey] = subvalue
        else:
            json_results[key] = value
    
    with open(filename, 'w') as f:
        json.dump(json_results, f, indent=2)
    
    print(f"Statistics saved to {filename}")

def print_summary(results):
    """Print a comprehensive summary of all statistics."""
    print("\n" + "="*80)
    print("COMPREHENSIVE NEURAL NETWORK STATISTICS SUMMARY")
    print("="*80)
    
    # Model counts
    print(f"\nMODEL COUNTS:")
    print(f"ANN Models: {len(results['neurons']['ann'])}")
    print(f"Rate SNN Models: {len(results['neurons']['rate_snn'])}")
    print(f"Temporal SNN Models: {len(results['neurons']['temporal_snn'])}")
    
    # Neurons summary
    print(f"\nNEURONS SUMMARY:")
    print(f"ANN - Average: {np.mean(results['neurons']['ann']):.0f}, Range: {min(results['neurons']['ann'])}-{max(results['neurons']['ann'])}")
    print(f"Rate SNN - Average: {np.mean(results['neurons']['rate_snn']):.0f}, Range: {min(results['neurons']['rate_snn'])}-{max(results['neurons']['rate_snn'])}")
    print(f"Temporal SNN - Average: {np.mean(results['neurons']['temporal_snn']):.0f}, Range: {min(results['neurons']['temporal_snn'])}-{max(results['neurons']['temporal_snn'])}")
    
    # Synapses summary
    print(f"\nSYNAPSES SUMMARY:")
    print(f"ANN - Average: {np.mean(results['synapses']['ann']):.0f}, Range: {min(results['synapses']['ann'])}-{max(results['synapses']['ann'])}")
    print(f"Rate SNN - Average: {np.mean(results['synapses']['rate_snn']):.0f}, Range: {min(results['synapses']['rate_snn'])}-{max(results['synapses']['rate_snn'])}")
    print(f"Temporal SNN - Average: {np.mean(results['synapses']['temporal_snn']):.0f}, Range: {min(results['synapses']['temporal_snn'])}-{max(results['synapses']['temporal_snn'])}")
    
    # Performance summary
    print(f"\nPERFORMANCE SUMMARY (Batch Size 64):")
    batch_key = 64 if 64 in results['inference_times']['ann'] else list(results['inference_times']['ann'].keys())[0]
    
    if batch_key in results['inference_times']['ann']:
        ann_time = np.mean(results['inference_times']['ann'][batch_key])
        rate_time = np.mean(results['inference_times']['rate_snn'][batch_key])
        temporal_time = np.mean(results['inference_times']['temporal_snn'][batch_key])
        
        print(f"ANN Inference Time: {ann_time:.4f}s")
        print(f"Rate SNN Inference Time: {rate_time:.4f}s ({rate_time/ann_time:.2f}x ANN)")
        print(f"Temporal SNN Inference Time: {temporal_time:.4f}s ({temporal_time/ann_time:.2f}x ANN)")
        
        if batch_key in results['spikes']['rate_snn']:
            rate_spikes = np.mean(results['spikes']['rate_snn'][batch_key])
            temporal_spikes = np.mean(results['spikes']['temporal_snn'][batch_key])
            
            print(f"\nSPIKE STATISTICS (Batch Size {batch_key}):")
            print(f"Rate SNN Total Spikes: {rate_spikes:.0f}")
            print(f"Temporal SNN Total Spikes: {temporal_spikes:.0f}")
            
            if rate_spikes > 0:
                print(f"Rate SNN Time per Spike: {rate_time/rate_spikes:.8f}s")
            if temporal_spikes > 0:
                print(f"Temporal SNN Time per Spike: {temporal_time/temporal_spikes:.8f}s")

if __name__ == "__main__":
    batch_sizes = [16, 32, 64, 128]
    
    print("Calculating comprehensive neural network statistics...")
    print("This includes: neurons, synapses, inference times, spike counts, and time per spike")
    
    # Calculate all statistics
    results = calculate_all_statistics(batch_sizes)
    
    # Save results
    save_statistics(results)
    
    # Create visualizations
    visualize_statistics(results)
    
    # Print summary
    print_summary(results)
    
    print("\nStatistical analysis completed successfully!")
    





